spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test;MODE=MySQL
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop # for test
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true # for test
    show_sql: true # for test

logging:
  level:
    org.hibernate.SQL: debug
