spring:
  profiles:
    default: test

---
spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:h2:tcp://localhost/~/test;TIME ZONE=UTC
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create # for test
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true # for test
    show_sql: true # for test

logging:
  level:
    org.hibernate.SQL: debug;

---
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:mysql://${DATABASE_URL}?serverTimezone=UTC
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

